import type { MgCampaign } from './types'

// ─── Dados curados das campanhas ────────────────────────────────────────────────
// Verificado contra a Wikipédia (EN/PT/ES) + fontes independentes em Jul/2026.
// score é SEMPRE [gols do nosso time, gols do adversário]. Confrontos de dois
// jogos da Libertadores viram duas entradas (ida/volta). Finais de jogo único
// têm leg=null. `penalties` só quando o confronto foi decidido nos pênaltis.
//
// Para crescer o catálogo: adicione um objeto seguindo o mesmo schema. Nada mais
// no app precisa mudar — telas, desafio do dia e pontuação leem daqui.

export const CAMPAIGNS_DATA: MgCampaign[] = [
  // ─── Seleção Brasileira — Copas do Mundo ──────────────────────────────────────
  {
    id: 'brasil-1958',
    competition: 'copa-do-mundo',
    team: 'Brasil',
    teamKind: 'selecao',
    teamCountryCode: 'br',
    year: 1958,
    topScorer: { name: 'Pelé', goals: 6 },
    scorerOptions: ['Vavá', 'Pelé', 'Zagallo', 'Nílton Santos'],
    sourceConfidence: 'high',
    path: [
      { stage: 'group', stageLabel: 'Fase de grupos', leg: null, opponent: 'Áustria', opponentCountryCode: 'at', score: [3, 0], penalties: null, note: null },
      { stage: 'group', stageLabel: 'Fase de grupos', leg: null, opponent: 'Inglaterra', opponentCountryCode: 'gb', score: [0, 0], penalties: null, note: 'Primeiro 0 a 0 da história das Copas' },
      { stage: 'group', stageLabel: 'Fase de grupos', leg: null, opponent: 'União Soviética', opponentCountryCode: 'ru', score: [2, 0], penalties: null, note: null },
      { stage: 'qf', stageLabel: 'Quartas de final', leg: null, opponent: 'País de Gales', opponentCountryCode: 'gb', score: [1, 0], penalties: null, note: 'Primeiro gol de Pelé em Copas' },
      { stage: 'sf', stageLabel: 'Semifinal', leg: null, opponent: 'França', opponentCountryCode: 'fr', score: [5, 2], penalties: null, note: 'Hat-trick de Pelé' },
      { stage: 'final', stageLabel: 'Final', leg: null, opponent: 'Suécia', opponentCountryCode: 'se', score: [5, 2], penalties: null, note: 'Råsunda, Solna' },
    ],
  },
  {
    id: 'brasil-1962',
    competition: 'copa-do-mundo',
    team: 'Brasil',
    teamKind: 'selecao',
    teamCountryCode: 'br',
    year: 1962,
    topScorer: { name: 'Garrincha', goals: 4 },
    scorerOptions: ['Vavá', 'Garrincha', 'Amarildo', 'Pelé'],
    sourceConfidence: 'high',
    path: [
      { stage: 'group', stageLabel: 'Fase de grupos', leg: null, opponent: 'México', opponentCountryCode: 'mx', score: [2, 0], penalties: null, note: null },
      { stage: 'group', stageLabel: 'Fase de grupos', leg: null, opponent: 'Tchecoslováquia', opponentCountryCode: 'cz', score: [0, 0], penalties: null, note: 'Pelé se lesionou nesta partida' },
      { stage: 'group', stageLabel: 'Fase de grupos', leg: null, opponent: 'Espanha', opponentCountryCode: 'es', score: [2, 1], penalties: null, note: null },
      { stage: 'qf', stageLabel: 'Quartas de final', leg: null, opponent: 'Inglaterra', opponentCountryCode: 'gb', score: [3, 1], penalties: null, note: null },
      { stage: 'sf', stageLabel: 'Semifinal', leg: null, opponent: 'Chile', opponentCountryCode: 'cl', score: [4, 2], penalties: null, note: null },
      { stage: 'final', stageLabel: 'Final', leg: null, opponent: 'Tchecoslováquia', opponentCountryCode: 'cz', score: [3, 1], penalties: null, note: 'Estádio Nacional, Santiago' },
    ],
  },
  {
    id: 'brasil-1970',
    competition: 'copa-do-mundo',
    team: 'Brasil',
    teamKind: 'selecao',
    teamCountryCode: 'br',
    year: 1970,
    topScorer: { name: 'Jairzinho', goals: 7 },
    scorerOptions: ['Pelé', 'Jairzinho', 'Rivelino', 'Tostão'],
    sourceConfidence: 'high',
    path: [
      { stage: 'group', stageLabel: 'Fase de grupos', leg: null, opponent: 'Tchecoslováquia', opponentCountryCode: 'cz', score: [4, 1], penalties: null, note: null },
      { stage: 'group', stageLabel: 'Fase de grupos', leg: null, opponent: 'Inglaterra', opponentCountryCode: 'gb', score: [1, 0], penalties: null, note: null },
      { stage: 'group', stageLabel: 'Fase de grupos', leg: null, opponent: 'Romênia', opponentCountryCode: 'ro', score: [3, 2], penalties: null, note: null },
      { stage: 'qf', stageLabel: 'Quartas de final', leg: null, opponent: 'Peru', opponentCountryCode: 'pe', score: [4, 2], penalties: null, note: null },
      { stage: 'sf', stageLabel: 'Semifinal', leg: null, opponent: 'Uruguai', opponentCountryCode: 'uy', score: [3, 1], penalties: null, note: null },
      { stage: 'final', stageLabel: 'Final', leg: null, opponent: 'Itália', opponentCountryCode: 'it', score: [4, 1], penalties: null, note: 'Azteca, Cidade do México — gol de Carlos Alberto' },
    ],
  },
  {
    id: 'brasil-1994',
    competition: 'copa-do-mundo',
    team: 'Brasil',
    teamKind: 'selecao',
    teamCountryCode: 'br',
    year: 1994,
    topScorer: { name: 'Romário', goals: 5 },
    scorerOptions: ['Bebeto', 'Romário', 'Raí', 'Branco'],
    sourceConfidence: 'high',
    path: [
      { stage: 'group', stageLabel: 'Fase de grupos', leg: null, opponent: 'Rússia', opponentCountryCode: 'ru', score: [2, 0], penalties: null, note: null },
      { stage: 'group', stageLabel: 'Fase de grupos', leg: null, opponent: 'Camarões', opponentCountryCode: 'cm', score: [3, 0], penalties: null, note: null },
      { stage: 'group', stageLabel: 'Fase de grupos', leg: null, opponent: 'Suécia', opponentCountryCode: 'se', score: [1, 1], penalties: null, note: null },
      { stage: 'r16', stageLabel: 'Oitavas de final', leg: null, opponent: 'Estados Unidos', opponentCountryCode: 'us', score: [1, 0], penalties: null, note: 'Gol de Bebeto' },
      { stage: 'qf', stageLabel: 'Quartas de final', leg: null, opponent: 'Países Baixos', opponentCountryCode: 'nl', score: [3, 2], penalties: null, note: null },
      { stage: 'sf', stageLabel: 'Semifinal', leg: null, opponent: 'Suécia', opponentCountryCode: 'se', score: [1, 0], penalties: null, note: 'Cabeçada de Romário' },
      { stage: 'final', stageLabel: 'Final', leg: null, opponent: 'Itália', opponentCountryCode: 'it', score: [0, 0], penalties: [3, 2], note: 'Rose Bowl, Pasadena — Brasil venceu nos pênaltis' },
    ],
  },
  {
    id: 'brasil-2002',
    competition: 'copa-do-mundo',
    team: 'Brasil',
    teamKind: 'selecao',
    teamCountryCode: 'br',
    year: 2002,
    topScorer: { name: 'Ronaldo', goals: 8 },
    scorerOptions: ['Rivaldo', 'Ronaldo', 'Ronaldinho', 'Roberto Carlos'],
    sourceConfidence: 'high',
    path: [
      { stage: 'group', stageLabel: 'Fase de grupos', leg: null, opponent: 'Turquia', opponentCountryCode: 'tr', score: [2, 1], penalties: null, note: null },
      { stage: 'group', stageLabel: 'Fase de grupos', leg: null, opponent: 'China', opponentCountryCode: 'cn', score: [4, 0], penalties: null, note: null },
      { stage: 'group', stageLabel: 'Fase de grupos', leg: null, opponent: 'Costa Rica', opponentCountryCode: 'cr', score: [5, 2], penalties: null, note: null },
      { stage: 'r16', stageLabel: 'Oitavas de final', leg: null, opponent: 'Bélgica', opponentCountryCode: 'be', score: [2, 0], penalties: null, note: null },
      { stage: 'qf', stageLabel: 'Quartas de final', leg: null, opponent: 'Inglaterra', opponentCountryCode: 'gb', score: [2, 1], penalties: null, note: 'Gol de falta de Ronaldinho' },
      { stage: 'sf', stageLabel: 'Semifinal', leg: null, opponent: 'Turquia', opponentCountryCode: 'tr', score: [1, 0], penalties: null, note: null },
      { stage: 'final', stageLabel: 'Final', leg: null, opponent: 'Alemanha', opponentCountryCode: 'de', score: [2, 0], penalties: null, note: 'Yokohama — dois gols de Ronaldo' },
    ],
  },

  // ─── Flamengo — Libertadores ───────────────────────────────────────────────────
  {
    id: 'flamengo-lib-1981',
    competition: 'libertadores',
    team: 'Flamengo',
    teamKind: 'clube',
    teamCountryCode: 'br',
    year: 1981,
    topScorer: { name: 'Zico', goals: 11 },
    scorerOptions: ['Nunes', 'Zico', 'Adílio', 'Lico'],
    sourceConfidence: 'high',
    path: [
      { stage: 'sf', stageLabel: 'Fase semifinal', leg: null, opponent: 'Deportivo Cali', opponentCountryCode: 'co', score: [1, 0], penalties: null, note: 'Em Cali' },
      { stage: 'sf', stageLabel: 'Fase semifinal', leg: null, opponent: 'Jorge Wilstermann', opponentCountryCode: 'bo', score: [2, 1], penalties: null, note: 'Em Cochabamba' },
      { stage: 'sf', stageLabel: 'Fase semifinal', leg: null, opponent: 'Deportivo Cali', opponentCountryCode: 'co', score: [3, 0], penalties: null, note: 'Maracanã' },
      { stage: 'sf', stageLabel: 'Fase semifinal', leg: null, opponent: 'Jorge Wilstermann', opponentCountryCode: 'bo', score: [4, 1], penalties: null, note: 'Maracanã' },
      { stage: 'final', stageLabel: 'Final', leg: 'ida', opponent: 'Cobreloa', opponentCountryCode: 'cl', score: [2, 1], penalties: null, note: 'Maracanã' },
      { stage: 'final', stageLabel: 'Final', leg: 'volta', opponent: 'Cobreloa', opponentCountryCode: 'cl', score: [0, 1], penalties: null, note: 'Santiago' },
      { stage: 'final', stageLabel: 'Final (desempate)', leg: null, opponent: 'Cobreloa', opponentCountryCode: 'cl', score: [2, 0], penalties: null, note: 'Montevidéu — dois gols de Zico' },
    ],
  },
  {
    id: 'flamengo-lib-2019',
    competition: 'libertadores',
    team: 'Flamengo',
    teamKind: 'clube',
    teamCountryCode: 'br',
    year: 2019,
    topScorer: { name: 'Gabigol', goals: 9 },
    scorerOptions: ['Bruno Henrique', 'Gabigol', 'Arrascaeta', 'Everton Ribeiro'],
    sourceConfidence: 'high',
    path: [
      { stage: 'r16', stageLabel: 'Oitavas de final', leg: 'ida', opponent: 'Emelec', opponentCountryCode: 'ec', score: [0, 2], penalties: null, note: 'Guayaquil' },
      { stage: 'r16', stageLabel: 'Oitavas de final', leg: 'volta', opponent: 'Emelec', opponentCountryCode: 'ec', score: [2, 0], penalties: [4, 3], note: 'Maracanã — 2 a 2 no agregado, Fla nos pênaltis' },
      { stage: 'qf', stageLabel: 'Quartas de final', leg: 'ida', opponent: 'Internacional', opponentCountryCode: 'br', score: [2, 0], penalties: null, note: 'Maracanã' },
      { stage: 'qf', stageLabel: 'Quartas de final', leg: 'volta', opponent: 'Internacional', opponentCountryCode: 'br', score: [1, 1], penalties: null, note: 'Porto Alegre' },
      { stage: 'sf', stageLabel: 'Semifinal', leg: 'ida', opponent: 'Grêmio', opponentCountryCode: 'br', score: [1, 1], penalties: null, note: 'Porto Alegre' },
      { stage: 'sf', stageLabel: 'Semifinal', leg: 'volta', opponent: 'Grêmio', opponentCountryCode: 'br', score: [5, 0], penalties: null, note: 'Maracanã' },
      { stage: 'final', stageLabel: 'Final', leg: null, opponent: 'River Plate', opponentCountryCode: 'ar', score: [2, 1], penalties: null, note: 'Lima — dois gols de Gabigol no fim' },
    ],
  },
  {
    id: 'flamengo-lib-2022',
    competition: 'libertadores',
    team: 'Flamengo',
    teamKind: 'clube',
    teamCountryCode: 'br',
    year: 2022,
    topScorer: { name: 'Pedro', goals: 12 },
    scorerOptions: ['Gabigol', 'Pedro', 'Bruno Henrique', 'Arrascaeta'],
    sourceConfidence: 'high',
    path: [
      { stage: 'r16', stageLabel: 'Oitavas de final', leg: 'ida', opponent: 'Deportes Tolima', opponentCountryCode: 'co', score: [1, 0], penalties: null, note: 'Ibagué' },
      { stage: 'r16', stageLabel: 'Oitavas de final', leg: 'volta', opponent: 'Deportes Tolima', opponentCountryCode: 'co', score: [7, 1], penalties: null, note: 'Maracanã' },
      { stage: 'qf', stageLabel: 'Quartas de final', leg: 'ida', opponent: 'Corinthians', opponentCountryCode: 'br', score: [2, 0], penalties: null, note: 'Neo Química Arena' },
      { stage: 'qf', stageLabel: 'Quartas de final', leg: 'volta', opponent: 'Corinthians', opponentCountryCode: 'br', score: [1, 0], penalties: null, note: 'Maracanã' },
      { stage: 'sf', stageLabel: 'Semifinal', leg: 'ida', opponent: 'Vélez Sarsfield', opponentCountryCode: 'ar', score: [4, 0], penalties: null, note: 'Buenos Aires' },
      { stage: 'sf', stageLabel: 'Semifinal', leg: 'volta', opponent: 'Vélez Sarsfield', opponentCountryCode: 'ar', score: [2, 1], penalties: null, note: 'Maracanã' },
      { stage: 'final', stageLabel: 'Final', leg: null, opponent: 'Athletico Paranaense', opponentCountryCode: 'br', score: [1, 0], penalties: null, note: 'Guayaquil — gol de Gabigol' },
    ],
  },
  {
    id: 'flamengo-lib-2025',
    competition: 'libertadores',
    team: 'Flamengo',
    teamKind: 'clube',
    teamCountryCode: 'br',
    year: 2025,
    topScorer: { name: 'Arrascaeta', goals: 2 },
    scorerOptions: ['Pedro', 'Arrascaeta', 'Bruno Henrique', 'Jorge Carrascal'],
    sourceConfidence: 'medium',
    sourceNote: 'Campanha com gols distribuídos; Arrascaeta e Pedro lideraram com 2 cada',
    path: [
      { stage: 'r16', stageLabel: 'Oitavas de final', leg: 'ida', opponent: 'Internacional', opponentCountryCode: 'br', score: [1, 0], penalties: null, note: 'Maracanã' },
      { stage: 'r16', stageLabel: 'Oitavas de final', leg: 'volta', opponent: 'Internacional', opponentCountryCode: 'br', score: [2, 0], penalties: null, note: 'Beira-Rio' },
      { stage: 'qf', stageLabel: 'Quartas de final', leg: 'ida', opponent: 'Estudiantes', opponentCountryCode: 'ar', score: [2, 1], penalties: null, note: 'Maracanã' },
      { stage: 'qf', stageLabel: 'Quartas de final', leg: 'volta', opponent: 'Estudiantes', opponentCountryCode: 'ar', score: [0, 1], penalties: [4, 2], note: 'La Plata — 2 a 2 no agregado, Fla nos pênaltis' },
      { stage: 'sf', stageLabel: 'Semifinal', leg: 'ida', opponent: 'Racing Club', opponentCountryCode: 'ar', score: [1, 0], penalties: null, note: 'Maracanã' },
      { stage: 'sf', stageLabel: 'Semifinal', leg: 'volta', opponent: 'Racing Club', opponentCountryCode: 'ar', score: [0, 0], penalties: null, note: 'Avellaneda' },
      { stage: 'final', stageLabel: 'Final', leg: null, opponent: 'Palmeiras', opponentCountryCode: 'br', score: [1, 0], penalties: null, note: 'Lima — gol de Danilo' },
    ],
  },

  // ─── Botafogo — Libertadores 2024 ─────────────────────────────────────────────
  {
    id: 'botafogo-lib-2024',
    competition: 'libertadores',
    team: 'Botafogo',
    teamKind: 'clube',
    teamCountryCode: 'br',
    year: 2024,
    topScorer: { name: 'Júnior Santos', goals: 10 },
    scorerOptions: ['Luiz Henrique', 'Júnior Santos', 'Igor Jesus', 'Thiago Almada'],
    sourceConfidence: 'high',
    path: [
      { stage: 'r16', stageLabel: 'Oitavas de final', leg: 'ida', opponent: 'Palmeiras', opponentCountryCode: 'br', score: [2, 1], penalties: null, note: 'Nilton Santos' },
      { stage: 'r16', stageLabel: 'Oitavas de final', leg: 'volta', opponent: 'Palmeiras', opponentCountryCode: 'br', score: [2, 2], penalties: null, note: 'Allianz Parque' },
      { stage: 'qf', stageLabel: 'Quartas de final', leg: 'ida', opponent: 'São Paulo', opponentCountryCode: 'br', score: [0, 0], penalties: null, note: 'Nilton Santos' },
      { stage: 'qf', stageLabel: 'Quartas de final', leg: 'volta', opponent: 'São Paulo', opponentCountryCode: 'br', score: [1, 1], penalties: [5, 4], note: 'Morumbi — Botafogo nos pênaltis' },
      { stage: 'sf', stageLabel: 'Semifinal', leg: 'ida', opponent: 'Peñarol', opponentCountryCode: 'uy', score: [5, 0], penalties: null, note: 'Nilton Santos' },
      { stage: 'sf', stageLabel: 'Semifinal', leg: 'volta', opponent: 'Peñarol', opponentCountryCode: 'uy', score: [1, 3], penalties: null, note: 'Montevidéu' },
      { stage: 'final', stageLabel: 'Final', leg: null, opponent: 'Atlético Mineiro', opponentCountryCode: 'br', score: [3, 1], penalties: null, note: 'Buenos Aires' },
    ],
  },

  // ─── Vasco da Gama — Libertadores 1998 ────────────────────────────────────────
  {
    id: 'vasco-lib-1998',
    competition: 'libertadores',
    team: 'Vasco',
    teamKind: 'clube',
    teamCountryCode: 'br',
    year: 1998,
    topScorer: { name: 'Luizão', goals: 7 },
    scorerOptions: ['Donizete', 'Luizão', 'Pedrinho', 'Juninho Pernambucano'],
    sourceConfidence: 'high',
    path: [
      { stage: 'sf', stageLabel: 'Semifinal', leg: 'ida', opponent: 'River Plate', opponentCountryCode: 'ar', score: [1, 0], penalties: null, note: 'São Januário' },
      { stage: 'sf', stageLabel: 'Semifinal', leg: 'volta', opponent: 'River Plate', opponentCountryCode: 'ar', score: [1, 1], penalties: null, note: 'Buenos Aires' },
      { stage: 'final', stageLabel: 'Final', leg: 'ida', opponent: 'Barcelona de Guayaquil', opponentCountryCode: 'ec', score: [2, 0], penalties: null, note: 'São Januário' },
      { stage: 'final', stageLabel: 'Final', leg: 'volta', opponent: 'Barcelona de Guayaquil', opponentCountryCode: 'ec', score: [2, 1], penalties: null, note: 'Guayaquil — primeiro título vascaíno' },
    ],
  },

  // ─── Fluminense — Libertadores 2023 ───────────────────────────────────────────
  {
    id: 'fluminense-lib-2023',
    competition: 'libertadores',
    team: 'Fluminense',
    teamKind: 'clube',
    teamCountryCode: 'br',
    year: 2023,
    topScorer: { name: 'Germán Cano', goals: 13 },
    scorerOptions: ['John Kennedy', 'Germán Cano', 'Jhon Arias', 'André'],
    sourceConfidence: 'high',
    path: [
      { stage: 'r16', stageLabel: 'Oitavas de final', leg: 'ida', opponent: 'Argentinos Juniors', opponentCountryCode: 'ar', score: [1, 1], penalties: null, note: 'Buenos Aires' },
      { stage: 'r16', stageLabel: 'Oitavas de final', leg: 'volta', opponent: 'Argentinos Juniors', opponentCountryCode: 'ar', score: [2, 0], penalties: null, note: 'Maracanã' },
      { stage: 'qf', stageLabel: 'Quartas de final', leg: 'ida', opponent: 'Olimpia', opponentCountryCode: 'py', score: [2, 0], penalties: null, note: 'Maracanã' },
      { stage: 'qf', stageLabel: 'Quartas de final', leg: 'volta', opponent: 'Olimpia', opponentCountryCode: 'py', score: [3, 1], penalties: null, note: 'Assunção' },
      { stage: 'sf', stageLabel: 'Semifinal', leg: 'ida', opponent: 'Internacional', opponentCountryCode: 'br', score: [2, 2], penalties: null, note: 'Maracanã' },
      { stage: 'sf', stageLabel: 'Semifinal', leg: 'volta', opponent: 'Internacional', opponentCountryCode: 'br', score: [2, 1], penalties: null, note: 'Beira-Rio' },
      { stage: 'final', stageLabel: 'Final', leg: null, opponent: 'Boca Juniors', opponentCountryCode: 'ar', score: [2, 1], penalties: null, note: 'Maracanã — gol de John Kennedy na prorrogação' },
    ],
  },
]
